"use client";
import { useCallback, useEffect, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Loader2 } from "lucide-react";
import { api, useI18n } from "@/lib/use-i18n";
import { dayKey, localStamp, toUTC } from "@/lib/calendar-time";
import { useApp } from "@/lib/store";
interface Post {id:string;brandId:string;platform:string;status:string;scheduledAt:string;timezone:string;caption:string|null;contentItem?:{id:string;title:string}|null}
const ZONES=["Asia/Yerevan","Europe/Moscow","Europe/London","America/New_York","UTC"];
export function ContentCalendar(){
 const {t,locale}=useI18n();const brand=useApp(s=>s.activeBrandId);const setView=useApp(s=>s.setView);
 const [posts,setPosts]=useState<Post[]>([]);const [mode,setMode]=useState("month");const [zone,setZone]=useState("Asia/Yerevan");const [month,setMonth]=useState(()=>new Date());const [platform,setPlatform]=useState("all");const [status,setStatus]=useState("all");const [selected,setSelected]=useState<Post|null>(null);const [stamp,setStamp]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{setPosts(await api<Post[]>("/api/schedule"));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);
 const visible=posts.filter(p=>(!brand||p.brandId===brand)&&(platform==="all"||p.platform===platform)&&(status==="all"||p.status===status));
 const first=new Date(Date.UTC(month.getFullYear(),month.getMonth(),1,12));const offset=(first.getUTCDay()+6)%7;const monthDays=Array.from({length:42},(_,i)=>new Date(Date.UTC(month.getFullYear(),month.getMonth(),1-offset+i,12)));
 const monday=new Date(Date.UTC(month.getFullYear(),month.getMonth(),month.getDate()-((month.getDay()+6)%7),12));const weekDays=Array.from({length:7},(_,i)=>new Date(monday.getTime()+i*86400000));const days=mode==="week"?weekDays:monthDays;
 const choose=(p:Post,day?:string)=>{setSelected(p);const old=localStamp(new Date(p.scheduledAt),zone);setStamp(day?`${day}T${old.split("T")[1]}`:old);setError("");};
 const move=async()=>{if(!selected||busy)return;setBusy(true);try{const utc=toUTC(stamp,zone);if(new Date(utc).getTime()<Date.now())throw new Error(t("signal.futureOnly"));await api(`/api/schedule/${selected.id}`,{method:"PATCH",body:JSON.stringify({action:"reschedule",scheduledAt:utc})});setSelected(null);await load();}catch(e){setError((e as Error).message==="DST_INVALID"?t("signal.dstError"):(e as Error).message);}finally{setBusy(false);}};
 const time=(p:Post)=>new Intl.DateTimeFormat(locale,{timeZone:zone,hour:"2-digit",minute:"2-digit"}).format(new Date(p.scheduledAt));
 return <section className="calendar-workspace space-y-5"><header className="flex items-center justify-between gap-3 flex-wrap"><h2 className="text-2xl font-semibold flex gap-2 items-center"><CalendarDays size={22}/>{t("signal.calendar")}</h2><div className="mode-switch">{["month","week","agenda"].map(v=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(v)}>{t(`signal.${v}`)}</button>)}</div></header>
 <div className="calendar-filters"><label>{t("signal.timezone")}<select value={zone} onChange={e=>setZone(e.target.value)}>{ZONES.map(z=><option key={z}>{z}</option>)}</select></label><label>{t("signal.platform")}<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">{t("signal.all")}</option>{["instagram","facebook","tiktok","telegram"].map(v=><option key={v}>{v}</option>)}</select></label><label>{t("signal.status")}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t("signal.all")}</option>{Array.from(new Set(posts.map(p=>p.status))).map(v=><option key={v}>{v}</option>)}</select></label></div>
 {error&&<p className="os-error" role="alert">{error}</p>}
 {loading?<Loader2 className="animate-spin" aria-label={t("common.loading")}/>:mode==="agenda"?<div className="os-panel p-4">{visible.length?visible.sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)).map(p=><button className="project-row" key={p.id} onClick={()=>choose(p)}><div><strong>{p.contentItem?.title??p.platform}</strong><small>{new Date(p.scheduledAt).toLocaleString(locale,{timeZone:zone})} · {zone}<br/>{new Date(p.scheduledAt).toISOString()} UTC</small></div><span className="status-label">{p.status}</span></button>):<div className="os-empty">{t("signal.calendarEmpty")}</div>}</div>:<div className="os-panel"><header className="calendar-heading"><button aria-label={t("signal.previous")} onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-(mode==="week"?0:1),mode==="week"?month.getDate()-7:1))}><ChevronLeft size={20}/></button><h3>{month.toLocaleDateString(locale,{month:"long",year:"numeric"})}</h3><button aria-label={t("signal.next")} onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+(mode==="week"?0:1),mode==="week"?month.getDate()+7:1))}><ChevronRight size={20}/></button></header><div className="calendar-grid">{days.map(d=>{const key=d.toISOString().slice(0,10);const list=visible.filter(p=>dayKey(new Date(p.scheduledAt),zone)===key);return <div className="calendar-day" key={key} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const p=visible.find(p=>p.id===e.dataTransfer.getData("text/plain"));if(p)choose(p,key);}}><time dateTime={key}>{d.toLocaleDateString(locale,{weekday:mode==="week"?"short":undefined,day:"numeric",timeZone:"UTC"})}</time>{list.map(p=><button key={p.id} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",p.id)} onClick={()=>choose(p)} className="calendar-post"><span>{time(p)} · {p.platform}</span><strong>{p.contentItem?.title??"—"}</strong><small>{p.status}</small></button>)}</div>})}</div></div>}
 {selected&&<div className="calendar-edit os-panel p-5 space-y-4"><h3>{selected.contentItem?.title}</h3><p className="text-muted-foreground text-sm">{selected.caption}</p><label className="grid gap-2">{t("signal.reschedule")} · {zone}<input type="datetime-local" className="os-select" value={stamp} onChange={e=>setStamp(e.target.value)}/></label><p className="text-xs text-muted-foreground">UTC: {selected.scheduledAt}</p>{visible.some(p=>p.id!==selected.id&&localStamp(new Date(p.scheduledAt),zone)===stamp)&&<p role="alert" className="os-error">{t("signal.timeConflict")}</p>}<div className="flex gap-2 flex-wrap"><button className="os-primary" disabled={busy} onClick={()=>void move()}>{t("common.save")}</button><button className="os-button" onClick={()=>{useApp.getState().setContentSeed(selected.contentItem?.id??null);setView("content");}}>{t("signal.edit")}</button><button className="os-button" onClick={()=>setSelected(null)}>{t("common.cancel")}</button></div></div>}
 </section>;
}
